### ISSUE TITLE
Wrong line commenting with `.gitignore` files

### ISSUE THREAD

**Issue by j-lakeman** [hyperupcall/vscode-assorted-languages#7]
When opening a `.gitignore` file and pressing the “line comment” key combo, `//` are inserted instead of `#`.

Regardless great extension! Cheers for your work! :+1:

**Comment by hyperupcall** [comment]
Thank you! This has been fixed by 60beb24729bdf2e9b566d505ba33541791f3b565 and was released in [v0.26.1](https://github.com/hyperupcall/vscode-assorted-languages/releases/tag/v0.26.1)

**Comment by j-lakeman** [comment]
Wow that was quick! Thanks mate!
